package com.sap.cap.esmapi.utilities.enums;

public enum EnumMessageType
{
    ERR_RATELIMIT, ERR_PAYLOAD, ERR_SRVCLOUDAPI, SUCC_ACC_CREATE, ERR_ACC_CREATE, SUCC_CASE_SUBM, ERR_CASE_CATG,
    ERR_ATTACHMENT, SUCC_CASE_CREATE, ERR_CASE_CREATE, ERR_UNAUTH_CASE_ACCESS, ERR_CASE_DET_FETCH, ERR_STAT_TRANS_CFG,
    SUCC_CASE_REPL_SUBM, ERR_CASE_REPL_SAVE, SUCC_CASE_REPL_SAVE, ERR_ATTACHMENT_SIZE, SUCC_CASE_CONFIRM_SAVE,
    ERR_CASE_CNF_SAV
}
